name: docker-builder
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u ${{ secrets.GHCR_USER }} -p ${{ secrets.GHCR_TOKEN }}

      - name: Build & tag image
        run: |
          docker build -f Dockerfile . \
            -t ghcr.io/netbootxyz/docker-builder:${{ env.IMAGE_VERSION }} \
            -t ghcr.io/netbootxyz/docker-builder:latest
      - name: Publish image
        run: |
          docker push ghcr.io/netbootxyz/docker-builder:${{ env.IMAGE_VERSION }}
          docker push ghcr.io/netbootxyz/docker-builder:latest
